{% set version = "2.6.0" %}

package:
  name: fabric
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fabric/fabric-{{ version }}.tar.gz
  sha256: 47f184b070272796fd2f9f0436799e18f2ccba4ee8ee587796fca192acd46cd2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - fab = fabric.main:program.run

requirements:
  host:
    - python
    - pip

  run:
    - python
    - invoke >=1.3,<2.0
    - paramiko >=2.4

test:
  imports:
    - fabric

  commands:
    - fab --help

about:
  home: http://fabfile.org
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Fabric is a simple, Pythonic tool for remote execution and deployment.'
  description: |
    Fabric is a Python library and command-line tool for streamlining the use
    of SSH for application deployment or systems administration tasks.
  doc_url: http://docs.fabfile.org/
  doc_source_url: https://github.com/fabric/fabric/blob/master/sites/docs/index.rst#id1
  dev_url: https://github.com/fabric/fabric

extra:
  recipe-maintainers:
    - pmlandwehr
