travis:
  secure:
    BINSTAR_TOKEN: fFQ7kJw/Z8gboZ2mGFn0K59eGXcxoIj4bh5CZZXSNHBBCDMy5ttaF+N4B+Ku4tYUg1V88i+XtopsoaYqJ5VcKpc1WFyvXhpowKHSZIVycweHCliLXysfLY0aGPT1S5qooWIv4IbzS6sTq0icERAfWEEXeWIYOBTwLW9M0m5AzTds5AywAwkwn+xtv5yEh8l/sHfxPwC3gHIx5yhPnKKu48Dyzuz246Ojj9UJZRrmA7tc+2jtjLBgrbl9Cn5XeMP5CZSUqQCc1Fo1o+sSMktyOHR3R9dSl2MKUSZ3oSnp6pkBWBQOpsKuObKuacSm/TEaqNiF54Gb/iNVoJPX0z1BN0Js34qvwm9JZNmDw9X5rnOK3HVSywz7T2aQ2RbTBwSeXOtvNFbYcsV7r54uHASFJE+V9K2wl9t5tgGb4fsHFqEqk2Bpmrq+SU5oKBGwaybO4FBcPLHZ4TS9SJINq0IQhhNebQEthW8bvlRwOrDLzg/H2dRrfnwMkTqikeAANjisC+gkHW1GufUqRkec+5gKiXHIFip2iyvpBbXZMfQ7P4I/Sge9QeFysquZBwyGHTISIjScjCobewQaEBgDQ2ETdKdL9bHwXiLM7NHH4+2k1xh9pUFKS1LvPQmhjCYsJWAneroPIjX4WvMnxJg4qt1C1zaXUXIrFh3ZtNbpMa2WNhg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
