travis:
  secure:
    BINSTAR_TOKEN: SUELQ6HHi19I9/QzXpWJeW+dp81w7v/29DYYTF+XiaEKp9ALouqyjuZZDca3aKj57+dA6Mix2ScDXsiay17QlWfT/pRkc1wfzPdFzHKAalHC3fZwiDRXjfgr5ViitN3SW5gkP/bda/7NV8CEodfiW6JxZjHXTZsegEjnq3lK7cuMih1ZjIriFMcTH4c43NthMIUTHNs+Ko3skz7SIWbL9s7SnCysxhvs0l/WPSAVKSoNT6cJAr9Fxo1VMldnx1vFE5pDobHs2067EU3oIwgx81IElEJ94oIgIl7QKAVbWy4qSzlhkqQsGmgm7uVqaUUlxuPRADg6reN3Mo1Cvnb3peN7w22fVhqewxOQvDiGOFpFg6ChnVgJPavPaAfQ6oerbmaxZNHCws15z0L5nzHBVVfISkpZVof0FwZhEPMoUBzOCEqyM/8UzykhX8u20skqQhXEiwwdpBXtxJdKgGUw26AoB0Az+30GlDYi9anMsnAP7juiPZuecgAHVeLHOk7Qm+gYnMinEu+M0zCDPrOPNfhrGxRk/nnM+Ox7hKSe/t9q3r64b9IfBBPtMVrQvzQqBQhnmLjAuN0bXSYUzdm67v2TMBq8LXTZZPcKQqP6cHRLe6EUsyyDI7XyupX4wdurS9+WyQtu3hOhZsMgXdf5RUtJTWex0tFA90RsVibC2qM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
